/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.calculation.ssdialog;

import de.elamx.clt.CLT_Laminate;
import de.elamx.clt.CLT_Layer;
import de.elamx.clt.CLT_LayerResult;
import de.elamx.laminate.Layer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.openide.util.NbPreferences;

/**
 *
 * @author Andreas Hauffe
 */
public class StressStrainDialogPanel extends javax.swing.JPanel implements ActionListener {

    private final CLT_Laminate laminate;

    /**
     * Creates new form StressStrainDialogPanel
     */
    @SuppressWarnings("this-escape")
    public StressStrainDialogPanel(CLT_Laminate laminate) {
        this.laminate = laminate;
        initComponents();
        globalRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.globalRadioButton", true));
        localRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.localRadioButton", false));
        xRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.xRadioButton", true));
        yRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.yRadioButton", false));
        xyRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.xyRadioButton", false));
        stressRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.stressRadioButton", true));
        strainRadioButton.setSelected(NbPreferences.forModule(StressStrainDialogPanel.class).getBoolean("StressStrainDialogPanel.strainRadioButton", false));
        
        globalRadioButton.addActionListener(this);
        localRadioButton.addActionListener(this);
        xRadioButton.addActionListener(this);
        yRadioButton.addActionListener(this);
        xyRadioButton.addActionListener(this);
        stressRadioButton.addActionListener(this);
        strainRadioButton.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueButtonGroup = new javax.swing.ButtonGroup();
        componentButtonGroup = new javax.swing.ButtonGroup();
        csButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        valuePanel = new javax.swing.JPanel();
        stressRadioButton = new javax.swing.JRadioButton();
        strainRadioButton = new javax.swing.JRadioButton();
        componentPanel = new javax.swing.JPanel();
        xRadioButton = new javax.swing.JRadioButton();
        yRadioButton = new javax.swing.JRadioButton();
        xyRadioButton = new javax.swing.JRadioButton();
        coordinateSystemPanel = new javax.swing.JPanel();
        globalRadioButton = new javax.swing.JRadioButton();
        localRadioButton = new javax.swing.JRadioButton();
        ssGraphicsPanel = new GraphicsPanel();

        setLayout(new java.awt.BorderLayout());

        valuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "valuePanel.title"))); // NOI18N

        valueButtonGroup.add(stressRadioButton);
        stressRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(stressRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.stressRadioButton.text")); // NOI18N

        valueButtonGroup.add(strainRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(strainRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.strainRadioButton.text")); // NOI18N

        javax.swing.GroupLayout valuePanelLayout = new javax.swing.GroupLayout(valuePanel);
        valuePanel.setLayout(valuePanelLayout);
        valuePanelLayout.setHorizontalGroup(
            valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stressRadioButton)
                    .addComponent(strainRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        valuePanelLayout.setVerticalGroup(
            valuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stressRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strainRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        componentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "componentPanel.title"))); // NOI18N

        componentButtonGroup.add(xRadioButton);
        xRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(xRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.xRadioButton.text")); // NOI18N

        componentButtonGroup.add(yRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(yRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.yRadioButton.text")); // NOI18N

        componentButtonGroup.add(xyRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(xyRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.xyRadioButton.text")); // NOI18N

        javax.swing.GroupLayout componentPanelLayout = new javax.swing.GroupLayout(componentPanel);
        componentPanel.setLayout(componentPanelLayout);
        componentPanelLayout.setHorizontalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentPanelLayout.createSequentialGroup()
                        .addComponent(xRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(xyRadioButton))
                    .addComponent(yRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        componentPanelLayout.setVerticalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xRadioButton)
                    .addComponent(xyRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        coordinateSystemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "coordinateSystemPanel.title"))); // NOI18N

        csButtonGroup.add(globalRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(globalRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.globalRadioButton.text")); // NOI18N

        csButtonGroup.add(localRadioButton);
        localRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(localRadioButton, org.openide.util.NbBundle.getMessage(StressStrainDialogPanel.class, "StressStrainDialogPanel.localRadioButton.text")); // NOI18N

        javax.swing.GroupLayout coordinateSystemPanelLayout = new javax.swing.GroupLayout(coordinateSystemPanel);
        coordinateSystemPanel.setLayout(coordinateSystemPanelLayout);
        coordinateSystemPanelLayout.setHorizontalGroup(
            coordinateSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinateSystemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coordinateSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(globalRadioButton)
                    .addComponent(localRadioButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        coordinateSystemPanelLayout.setVerticalGroup(
            coordinateSystemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinateSystemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(globalRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(localRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(valuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coordinateSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(componentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valuePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coordinateSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout ssGraphicsPanelLayout = new javax.swing.GroupLayout(ssGraphicsPanel);
        ssGraphicsPanel.setLayout(ssGraphicsPanelLayout);
        ssGraphicsPanelLayout.setHorizontalGroup(
            ssGraphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        ssGraphicsPanelLayout.setVerticalGroup(
            ssGraphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        add(ssGraphicsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup componentButtonGroup;
    private javax.swing.JPanel componentPanel;
    private javax.swing.JPanel coordinateSystemPanel;
    private javax.swing.ButtonGroup csButtonGroup;
    private javax.swing.JRadioButton globalRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton localRadioButton;
    private javax.swing.JPanel ssGraphicsPanel;
    private javax.swing.JRadioButton strainRadioButton;
    private javax.swing.JRadioButton stressRadioButton;
    private javax.swing.ButtonGroup valueButtonGroup;
    private javax.swing.JPanel valuePanel;
    private javax.swing.JRadioButton xRadioButton;
    private javax.swing.JRadioButton xyRadioButton;
    private javax.swing.JRadioButton yRadioButton;
    // End of variables declaration//GEN-END:variables

    private CLT_LayerResult[] results;

    public void setResults(CLT_LayerResult[] results) {
        this.results = results;
    }

    private void setStresses(int value) {

        CLT_Layer[] layers = laminate.getCLTLayers();

        int numLayers = layers.length;
        double[] thick = new double[numLayers];
        double[] angle = new double[numLayers];
        double[] uVals = new double[numLayers];
        double[] lVals = new double[numLayers];
        boolean local = localRadioButton.isSelected();

        for (int ii = 0; ii < numLayers; ii++) {
            Layer l = layers[ii].getLayer();
            thick[ii] = l.getThickness();
            angle[ii] = l.getAngle() * Math.PI / 180.0;
            if (stressRadioButton.isSelected()) {
                if (local) {
                    uVals[ii] = results[ii].getSss_upper().getStress()[value];
                    lVals[ii] = results[ii].getSss_lower().getStress()[value];
                } else {
                    uVals[ii] = results[ii].getSss_upper_glo().getStress()[value];
                    lVals[ii] = results[ii].getSss_lower_glo().getStress()[value];
                }
            } else {
                if (local) {
                    uVals[ii] = results[ii].getSss_upper().getStrain()[value];
                    lVals[ii] = results[ii].getSss_lower().getStrain()[value];
                } else {
                    uVals[ii] = results[ii].getSss_upper_glo().getStrain()[value];
                    lVals[ii] = results[ii].getSss_lower_glo().getStrain()[value];
                }
            }
        }

        ((GraphicsPanel) ssGraphicsPanel).setValues(uVals, lVals, thick, numLayers, angle);
    }

    private void setGraphic() {
        if (xRadioButton.isSelected()) {
            setStresses(0);
        } else if (yRadioButton.isSelected()) {
            setStresses(1);
        } else if (xyRadioButton.isSelected()) {
            setStresses(2);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        setGraphic();
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.globalRadioButton", globalRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.localRadioButton", localRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.xRadioButton", xRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.yRadioButton", yRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.xyRadioButton", xyRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.stressRadioButton", stressRadioButton.isSelected());
        NbPreferences.forModule(StressStrainDialogPanel.class).putBoolean("StressStrainDialogPanel.strainRadioButton", strainRadioButton.isSelected());
    }
}
