/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.calculation.info;

import de.elamx.clt.CLT_Laminate;
import de.elamx.core.GlobalProperties;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import javax.swing.JLabel;

/**
 *
 * @author Andreas Hauffe
 */
public class EngineeringConstantsPanel extends javax.swing.JPanel {

    private final DecimalFormat stiffnessFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STIFFNESS);
    private final DecimalFormat poissonFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_POISSONRATIO);
    private final DecimalFormat thicknessFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_THICKNESS);
    private final DecimalFormat weightFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DENSITY);
    private final CopyMouseListener copyList = new CopyMouseListener();

    /**
     * Creates new form EngineeringConstantsPanel
     */
    @SuppressWarnings("this-escape")
    public EngineeringConstantsPanel() {
        initComponents();
    }

    public void setValues(CLT_Laminate laminate) {
        exBendwP.setText(stiffnessFormat.format(laminate.getExBendSimple()));
        exBendwoP.setText(stiffnessFormat.format(laminate.getExBendFixed()));
        exMembwP.setText(stiffnessFormat.format(laminate.getExSimple()));
        exMembwoP.setText(stiffnessFormat.format(laminate.getExFixed()));
        eyBendwP.setText(stiffnessFormat.format(laminate.getEyBendSimple()));
        eyBendwoP.setText(stiffnessFormat.format(laminate.getEyBendFixed()));
        eyMembwP.setText(stiffnessFormat.format(laminate.getEySimple()));
        eyMembwoP.setText(stiffnessFormat.format(laminate.getEyFixed()));
        gxyBendwP.setText(stiffnessFormat.format(laminate.getGBendSimple()));
        gxyBendwoP.setText(stiffnessFormat.format(laminate.getGBendFixed()));
        gxyMembwP.setText(stiffnessFormat.format(laminate.getGSimple()));
        gxyMembwoP.setText(stiffnessFormat.format(laminate.getGFixed()));

        nuexyBendwP.setText(poissonFormat.format(laminate.getNuxyBendSimple()));
        //nuexyBendwoP.setText(poissonFormat.format(laminate.getNuxyBendFixed()));
        nuexyMembwP.setText(poissonFormat.format(laminate.getNuxySimple()));
        //nuexyMembwoP.setText(poissonFormat.format(laminate.getNuxyFixed()));
        nueyxBendwP.setText(poissonFormat.format(laminate.getNuyxBendSimple()));
        //nueyxBendwoP.setText(poissonFormat.format(laminate.getNuyxBendFixed()));
        nueyxMembwP.setText(poissonFormat.format(laminate.getNuyxSimple()));
        //nueyxMembwoP.setText(poissonFormat.format(laminate.getNuyxFixed()));

        tges.setText(thicknessFormat.format(laminate.getTges()));

        areaWeight.setText(weightFormat.format(laminate.getAreaWeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        exMembwoP = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        exBendwoP = new javax.swing.JLabel();
        eyMembwoP = new javax.swing.JLabel();
        eyBendwoP = new javax.swing.JLabel();
        gxyMembwoP = new javax.swing.JLabel();
        gxyBendwoP = new javax.swing.JLabel();
        nuexyMembwoP = new javax.swing.JLabel();
        nuexyBendwoP = new javax.swing.JLabel();
        nueyxMembwoP = new javax.swing.JLabel();
        nueyxBendwoP = new javax.swing.JLabel();
        tges = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        exMembwP = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        exBendwP = new javax.swing.JLabel();
        eyMembwP = new javax.swing.JLabel();
        eyBendwP = new javax.swing.JLabel();
        gxyMembwP = new javax.swing.JLabel();
        gxyBendwP = new javax.swing.JLabel();
        nuexyMembwP = new javax.swing.JLabel();
        nuexyBendwP = new javax.swing.JLabel();
        nueyxMembwP = new javax.swing.JLabel();
        nueyxBendwP = new javax.swing.JLabel();
        areaWeight = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstants"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.exLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.eyLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.gLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.nuxyLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.nuyxLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.tgesLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel11.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel12.text")); // NOI18N

        exMembwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(exMembwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.exMembwoP.text")); // NOI18N
        exMembwoP.addMouseListener(copyList);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.membranLabel.text")); // NOI18N

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.bendingLabel.text")); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.withoutPoissonLabel.text")); // NOI18N

        exBendwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(exBendwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.exBendwoP.text")); // NOI18N
        exBendwoP.addMouseListener(copyList);

        eyMembwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(eyMembwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.eyMembwoP.text")); // NOI18N
        eyMembwoP.addMouseListener(copyList);

        eyBendwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(eyBendwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.eyBendwoP.text")); // NOI18N
        eyBendwoP.addMouseListener(copyList);

        gxyMembwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(gxyMembwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.gxyMembwoP.text")); // NOI18N
        gxyMembwoP.addMouseListener(copyList);

        gxyBendwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(gxyBendwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.gxyBendwoP.text")); // NOI18N
        gxyBendwoP.addMouseListener(copyList);

        nuexyMembwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nuexyMembwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nuexyMembwoP.text")); // NOI18N

        nuexyBendwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nuexyBendwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nuexyBendwoP.text")); // NOI18N

        nueyxMembwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nueyxMembwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nueyxMembwoP.text")); // NOI18N

        nueyxBendwoP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nueyxBendwoP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nueyxBendwoP.text")); // NOI18N

        tges.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(tges, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.tges.text")); // NOI18N
        tges.addMouseListener(copyList);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel16, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.membranLabel.text")); // NOI18N

        exMembwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(exMembwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.exMembwP.text")); // NOI18N
        exMembwP.addMouseListener(copyList);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel17, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.bendingLabel.text")); // NOI18N

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel18, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineerConstantsPanel.withPoissonLabel.text")); // NOI18N

        exBendwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(exBendwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.exBendwP.text")); // NOI18N
        exBendwP.addMouseListener(copyList);

        eyMembwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(eyMembwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.eyMembwP.text")); // NOI18N
        eyMembwP.addMouseListener(copyList);

        eyBendwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(eyBendwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.eyBendwP.text")); // NOI18N
        eyBendwP.addMouseListener(copyList);

        gxyMembwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(gxyMembwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.gxyMembwP.text")); // NOI18N
        gxyMembwP.addMouseListener(copyList);

        gxyBendwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(gxyBendwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.gxyBendwP.text")); // NOI18N
        gxyBendwP.addMouseListener(copyList);

        nuexyMembwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nuexyMembwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nuexyMembwP.text")); // NOI18N
        nuexyMembwP.addMouseListener(copyList);

        nuexyBendwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nuexyBendwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nuexyBendwP.text")); // NOI18N
        nuexyBendwP.addMouseListener(copyList);

        nueyxMembwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nueyxMembwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nueyxMembwP.text")); // NOI18N
        nueyxMembwP.addMouseListener(copyList);

        nueyxBendwP.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(nueyxBendwP, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.nueyxBendwP.text")); // NOI18N
        nueyxBendwP.addMouseListener(copyList);

        areaWeight.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(areaWeight, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.areaWeight.text")); // NOI18N
        areaWeight.addMouseListener(copyList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel21, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.aeraWeightLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel22, org.openide.util.NbBundle.getMessage(EngineeringConstantsPanel.class, "EngineeringConstantsPanel.jLabel22.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nuexyMembwoP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gxyMembwoP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eyMembwoP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exMembwoP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nueyxMembwoP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(exBendwoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eyBendwoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gxyBendwoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nuexyBendwoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nueyxBendwoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nueyxMembwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuexyMembwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eyMembwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exMembwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gxyMembwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nueyxBendwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuexyBendwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gxyBendwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eyBendwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exBendwP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(exBendwoP)
                            .addComponent(exMembwoP)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exMembwP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exBendwP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(eyMembwoP)
                    .addComponent(eyBendwoP)
                    .addComponent(eyMembwP)
                    .addComponent(eyBendwP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(gxyMembwoP)
                    .addComponent(gxyBendwoP)
                    .addComponent(gxyMembwP)
                    .addComponent(gxyBendwP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(nuexyMembwoP)
                    .addComponent(nuexyBendwoP)
                    .addComponent(nuexyMembwP)
                    .addComponent(nuexyBendwP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(nueyxMembwoP)
                    .addComponent(nueyxBendwoP)
                    .addComponent(nueyxMembwP)
                    .addComponent(nueyxBendwP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(areaWeight)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaWeight;
    private javax.swing.JLabel exBendwP;
    private javax.swing.JLabel exBendwoP;
    private javax.swing.JLabel exMembwP;
    private javax.swing.JLabel exMembwoP;
    private javax.swing.JLabel eyBendwP;
    private javax.swing.JLabel eyBendwoP;
    private javax.swing.JLabel eyMembwP;
    private javax.swing.JLabel eyMembwoP;
    private javax.swing.JLabel gxyBendwP;
    private javax.swing.JLabel gxyBendwoP;
    private javax.swing.JLabel gxyMembwP;
    private javax.swing.JLabel gxyMembwoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nuexyBendwP;
    private javax.swing.JLabel nuexyBendwoP;
    private javax.swing.JLabel nuexyMembwP;
    private javax.swing.JLabel nuexyMembwoP;
    private javax.swing.JLabel nueyxBendwP;
    private javax.swing.JLabel nueyxBendwoP;
    private javax.swing.JLabel nueyxMembwP;
    private javax.swing.JLabel nueyxMembwoP;
    private javax.swing.JLabel tges;
    // End of variables declaration//GEN-END:variables

    private class CopyMouseListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            Toolkit.getDefaultToolkit()
                    .getSystemClipboard()
                    .setContents(
                            new StringSelection(((JLabel) e.getSource()).getText()),
                            null
                    );
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

    }
}
