/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.plateui.stiffenerui.wizard;

import de.elamx.clt.plateui.stiffenerui.StiffenerDefinitionService;
import javax.swing.ImageIcon;
import org.openide.nodes.Node;
import org.openide.util.NbBundle;

/**
 *
 * @author Andreas Hauffe
 */
public class StiffenerDefinitionVisualPanel extends javax.swing.JPanel {
    
    private StiffenerDefinitionService service;

    /**
     * Creates new form StiffenerDefintionVisualPanel
     */
    @SuppressWarnings("this-escape")
    public StiffenerDefinitionVisualPanel() {
        initComponents();
    }
    
    @Override
    public String getName() {
        return NbBundle.getMessage(StiffenerDefinitionVisualPanel.class, "StiffenerDefinitionVisualPanel.Title");
    }
    
    public GeneralStiffenerInputPanel getGeneralPanel(){
        return generalStiffenerInputPanel1;
    }
    
    public void setStiffenerDefinitionService(StiffenerDefinitionService service){
        this.service = service;
        updateView();
    }
    
    public StiffenerDefinitionService getStiffenerDefinitionService(){
        flush();
        return service;
    }
    
    public void flush(){
        service.setName(generalStiffenerInputPanel1.getStiffenerName());
        service.setDirection(generalStiffenerInputPanel1.getDirection());
        service.setPosition(generalStiffenerInputPanel1.getPosition().doubleValue());
    }
    
    public void updateView(){
        generalStiffenerInputPanel1.setStiffenerName(service.getName());
        generalStiffenerInputPanel1.setDirection(service.getDirection());
        generalStiffenerInputPanel1.setPosition(service.getPosition());
        propertySheet1.setNodes(new Node[]{new StiffenerDefinitionServiceNode(service)});
        ImageIcon image = service.getGeometryParameterImage();
        imageLabel.setIcon(image);
        imageLabel.setText(null);
        if (image == null){
            imageLabel.setVisible(false);
        }else{
            imageLabel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalStiffenerInputPanel1 = new de.elamx.clt.plateui.stiffenerui.wizard.GeneralStiffenerInputPanel();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        propertySheet1 = new org.openide.explorer.propertysheet.PropertySheet();

        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(StiffenerDefinitionVisualPanel.class, "StiffenerDefinitionVisualPanel.dataPanel.title"))); // NOI18N

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(imageLabel, org.openide.util.NbBundle.getMessage(StiffenerDefinitionVisualPanel.class, "StiffenerDefinitionVisualPanel.imageLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propertySheet1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(propertySheet1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalStiffenerInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalStiffenerInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.elamx.clt.plateui.stiffenerui.wizard.GeneralStiffenerInputPanel generalStiffenerInputPanel1;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private org.openide.explorer.propertysheet.PropertySheet propertySheet1;
    // End of variables declaration//GEN-END:variables
}
