/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.cutoutui;

import de.elamx.clt.CLT_Laminate;
import de.elamx.clt.cutout.Cutout;
import de.elamx.clt.cutout.CutoutGeometry;
import de.elamx.clt.cutout.CutoutResult;
import java.awt.EventQueue;
import org.jfree.chart.JFreeChart;
import org.netbeans.api.progress.ProgressHandle;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;
import org.openide.util.RequestProcessor;

/**
 *
 * @author raedel
 */
public class ControlPanel extends javax.swing.JPanel {
    
    private final CutoutModuleData data;
    private JFreeChart chart;
    
    /**
     * Creates new customizer ControlPanel
     */
    public ControlPanel() {
        this(null, null);
    }
    
    @SuppressWarnings("this-escape")
    public ControlPanel(CutoutModuleData data, JFreeChart chart){
        this.data  = data;
        this.chart = chart;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcButton = new javax.swing.JButton();
        resultPanel = new ResultPanel(data, chart);
        inputPanel = new InputPanel(data);

        calcButton.setText(org.openide.util.NbBundle.getMessage(ControlPanel.class, "ControlPanel.calcButton.text")); // NOI18N
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        calcButton.setEnabled(false);
        resultPanel.initListeners();
        final CLT_Laminate laminat = data.getLaminat().getLookup().lookup(CLT_Laminate.class);
        final ProgressHandle ph = ProgressHandle.createSystemHandle(NbBundle.getMessage(ControlPanel.class, "Task.cutoutcalc"), null);
        if (checkInput(laminat)){
            RequestProcessor.getDefault().post(new Runnable() {
                @Override
                public void run() {
                    ph.start();
                    final CutoutResult result = Cutout.calc(laminat, data.getCutoutInput());
                    EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            data.setResult(result);
                            calcButton.setEnabled(true);
                            ph.finish();
                        }
                    });
                }
            });
        }else{
            calcButton.setEnabled(true);
        }
    }//GEN-LAST:event_calcButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private de.elamx.clt.cutoutui.InputPanel inputPanel;
    private de.elamx.clt.cutoutui.ResultPanel resultPanel;
    // End of variables declaration//GEN-END:variables

    public void cleanup(){
        resultPanel.cleanup();
    }
    
    private boolean checkInput(CLT_Laminate laminat) {
        if (laminat.getCLTLayers().length == 0){
            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(NbBundle.getMessage(ControlPanel.class, "Warning.nolaminate"), NotifyDescriptor.WARNING_MESSAGE));
            return false;
        }
        
        CutoutGeometry cg = data.getCutoutInput().getCutoutGeometry();
        double ratio = cg.getA()/cg.getB();
        if (ratio < 1.0/cg.getMaximumAspectRatio() || cg.getMaximumAspectRatio() < ratio){
            DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(NbBundle.getMessage(ControlPanel.class, "Warning.aspectratio"), NotifyDescriptor.WARNING_MESSAGE));
        }
        return true;
    }
}
