/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.plateui.deformation.load;

import de.elamx.clt.plate.DeformationInput;
import de.elamx.clt.plate.Mechanical.PointLoad;
import de.elamx.clt.plate.Mechanical.SurfaceLoad_const_full;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.text.MessageFormat;
import javax.swing.ActionMap;
import javax.swing.JPopupMenu;
import org.netbeans.swing.outline.DefaultOutlineModel;
import org.openide.DialogDisplayer;
import org.openide.WizardDescriptor;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.NodePopupFactory;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

/**
 *
 * @author Andreas Hauffe
 */
public class LoadPanel extends javax.swing.JPanel implements ExplorerManager.Provider, Lookup.Provider {

    private final ExplorerManager explorerManager = new ExplorerManager();
    private final DeformationInput input;
    private final Lookup lookup;

    /**
     * Creates new form LoadPanel
     */
    public LoadPanel() {
        this(null);
    }

    /**
     * Creates new form LoadPanel
     */
    @SuppressWarnings("this-escape")
    public LoadPanel(DeformationInput input) {
        this.input = input;
        lookup = ExplorerUtils.createLookup(explorerManager, new ActionMap());
        initComponents();
        initView();
    }

    private void initView() {
        outlineView.setPropertyColumns(TransverseLoadNode.LOAD_TYPE, NbBundle.getMessage(LoadPanel.class, "TransverseLoadNode.loadtype"));
        ((DefaultOutlineModel) outlineView.getOutline().getModel()).setNodesColumnLabel(NbBundle.getMessage(LoadPanel.class, "TransverseLoadNode.Name"));
        outlineView.getOutline().setRootVisible(false);
        NodePopupFactory npf = new NodePopupFactory() {
            @Override
            public JPopupMenu createPopupMenu(int row, int column, Node[] selectedNodes, Component component) {
                return super.createPopupMenu(row, column, selectedNodes, component);
            }
        };
        outlineView.setNodePopupFactory(npf);
        outlineView.getNodePopupFactory().setShowQuickFilter(false);
        if (input != null) {
            explorerManager.setRootContext(new LoadsNode(input));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        outlineView = new org.openide.explorer.view.OutlineView();

        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(addButton, org.openide.util.NbBundle.getMessage(LoadPanel.class, "LoadPanel.addButton.text")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, java.awt.BorderLayout.PAGE_END);
        add(outlineView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //input.addLoad(new PointLoad("Load", 0.0, 0.0, 1.0));
        NewLoadWizardIterator newLoadWizardIter = new NewLoadWizardIterator();
        WizardDescriptor wiz = new WizardDescriptor(newLoadWizardIter);
        newLoadWizardIter.initialize(wiz);
        // {0} will be replaced by WizardDescriptor.Panel.getComponent().getName()
        // {1} will be replaced by WizardDescriptor.Iterator.name()
        wiz.setTitleFormat(new MessageFormat("{0} ({1})"));
        wiz.setTitle(NbBundle.getMessage(LoadPanel.class, "LoadWizard.title"));
        if (DialogDisplayer.getDefault().notify(wiz) == WizardDescriptor.FINISH_OPTION) {
            int loadType = ((Integer)wiz.getProperty("loadtype"));
            if (loadType == ForceTypeVisualPanel.LOAD_POINT){
                double xPos = ((Number)wiz.getProperty("xposition")).doubleValue();
                double yPos = ((Number)wiz.getProperty("yposition")).doubleValue();
                double force = ((Number)wiz.getProperty("force")).doubleValue();
                input.addLoad(new PointLoad("PointLoad", xPos, yPos, force));
            }else if (loadType == ForceTypeVisualPanel.LOAD_SURFACE){
                double force = ((Number)wiz.getProperty("force")).doubleValue();
                input.addLoad(new SurfaceLoad_const_full("SurfaceLoad", force));
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private org.openide.explorer.view.OutlineView outlineView;
    // End of variables declaration//GEN-END:variables
    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public Lookup getLookup() {
        return lookup;
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        try {
            explorerManager.setSelectedNodes(new Node[0]);
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    @Override
    public void addNotify() {
        super.addNotify();
        ExplorerUtils.activateActions(explorerManager, true);
    }

    @Override
    public void removeNotify() {
        ExplorerUtils.activateActions(explorerManager, false);
        super.removeNotify();
    }
}
