/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.plateui.deformation.load;

import de.elamx.core.GlobalProperties;
import java.text.DecimalFormat;
import javax.swing.JPanel;
import javax.swing.text.NumberFormatter;
import org.openide.util.NbBundle;

public final class SurfaceLoad_const_fullVisualPanel extends JPanel {
    
    private static final DecimalFormat forceFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_FORCE);

    /**
     * Creates new form NewLoadVisualPanel2
     */
    public SurfaceLoad_const_fullVisualPanel() {
        initComponents();
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(ForceTypeVisualPanel.class, "LoadDataPanel.title");
    }
    
    public Number getForce(){
        return (Number)forceField.getValue();
    }
    
    public void setForce(Number value){
        forceField.setValue(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forceLabel = new javax.swing.JLabel();
        forceField = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(forceLabel, org.openide.util.NbBundle.getMessage(SurfaceLoad_const_fullVisualPanel.class, "SurfaceLoad_const_fullVisualPanel.forceLabel.text")); // NOI18N

        forceField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new NumberFormatter(forceFormat)));
        forceField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        forceField.setText(org.openide.util.NbBundle.getMessage(SurfaceLoad_const_fullVisualPanel.class, "SurfaceLoad_const_fullVisualPanel.forceField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forceLabel)
                .addGap(29, 29, 29)
                .addComponent(forceField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forceLabel)
                    .addComponent(forceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField forceField;
    private javax.swing.JLabel forceLabel;
    // End of variables declaration//GEN-END:variables
}
