/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.export.Abaqus;

import de.elamx.export.Export;
import de.elamx.export.ExportOptions;
import de.elamx.export.ExportOptionsPanel;
import de.elamx.laminate.Laminat;
import org.openide.util.NbPreferences;

/**
 *
 * @author Andreas Hauffe
 */
public class AbaqusExportOptionsPanel extends ExportOptionsPanel {

    private Laminat laminate;
    
    /**
     * Creates new form AbaqusExportOptionsPanel
     */
    @SuppressWarnings("this-escape")
    public AbaqusExportOptionsPanel() {
        initComponents();
        hygrothermalCheckBox.setSelected(NbPreferences.forModule(AbaqusExportOptionsPanel.class).getBoolean("AbaqusExportOptionsPanel.hygrothermnal", false));
        strengthCheckBox.setSelected(NbPreferences.forModule(AbaqusExportOptionsPanel.class).getBoolean("AbaqusExportOptionsPanel.strength", false));
    }
    
    public AbaqusExportOptionsPanel(Laminat laminate) {
        this();
        this.laminate = laminate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hygrothermalCheckBox = new javax.swing.JCheckBox();
        strengthCheckBox = new javax.swing.JCheckBox();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AbaqusExportOptionsPanel.class, "additionalExportPanel.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hygrothermalCheckBox, org.openide.util.NbBundle.getMessage(AbaqusExportOptionsPanel.class, "AbaqusExportOptionsPanel.hygrothermalCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(strengthCheckBox, org.openide.util.NbBundle.getMessage(AbaqusExportOptionsPanel.class, "AbaqusExportOptionsPanel.strengthCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hygrothermalCheckBox)
                    .addComponent(strengthCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hygrothermalCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strengthCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox hygrothermalCheckBox;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox strengthCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public Export<? extends ExportOptions> getExport() {
        AbaqusExport export = new AbaqusExport(laminate);
        AbaqusExportOptions options = export.getOptions();
        options.setHygrothermal(hygrothermalCheckBox.isSelected());
        options.setStrength(strengthCheckBox.isSelected());
        NbPreferences.forModule(AbaqusExportOptionsPanel.class).putBoolean("AbaqusExportOptionsPanel.hygrothermnal", hygrothermalCheckBox.isSelected());
        NbPreferences.forModule(AbaqusExportOptionsPanel.class).putBoolean("AbaqusExportOptionsPanel.strength", strengthCheckBox.isSelected());
        return export;
    }
}
