/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.failureview3d;

import de.elamx.core.GlobalProperties;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.NumberFormatter;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.NbBundle;

/**
 *
 * @author Andreas Hauffe
 */
public class VTKImportPanel extends javax.swing.JPanel {
    
    private static final DecimalFormat doubleFormat  = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DOUBLE);

    /**
     * Creates new form ImagePropertyPanel
     */
    public VTKImportPanel(String filename, double scale) {
        initComponents();
        filenameField.setText(filename);
        scaleFactorField.setValue(scale);
    }

    public String getFilename() {
        return filenameField.getText();
    }

    public void setFilename(String filename) {
        filenameField.setText(filename);
    }
    
    public double getScale() {
        return ((Number) scaleFactorField.getValue()).doubleValue();
    }

    public void setScale(double scale) {
        scaleFactorField.setValue(scale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scaleFactorField = new javax.swing.JFormattedTextField();
        filenameField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(VTKImportPanel.class, "VTKImportPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(VTKImportPanel.class, "VTKImportPanel.jLabel2.text")); // NOI18N

        scaleFactorField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new NumberFormatter(doubleFormat)));
        scaleFactorField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        filenameField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        filenameField.setText(org.openide.util.NbBundle.getMessage(VTKImportPanel.class, "VTKImportPanel.filenameField.text")); // NOI18N

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elamx/failureview3d/resources/fileopen.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(openButton, org.openide.util.NbBundle.getMessage(VTKImportPanel.class, "VTKImportPanel.openButton.text")); // NOI18N
        openButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filenameField, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openButton))
                    .addComponent(scaleFactorField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(scaleFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed

        File basePath = new File(System.getProperty("user.home"));
        File file = new FileChooserBuilder("vtkImport-dir").setTitle(NbBundle.getMessage(VTKImportPanel.class, "OpenFileDialog.Title")).
                setDefaultWorkingDirectory(basePath).setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                String name = f.getName().toLowerCase();
                return name.endsWith(".vtk") || name.endsWith(".VTK") || (f.isDirectory() && !f.isHidden());
            }

            @Override
            public String getDescription() {
                return NbBundle.getMessage(VTKImportPanel.class, "OpenFileDialog.Description");
            }
        }).setSelectionApprover(new FileChooserBuilder.SelectionApprover() {

            @Override
            public boolean approve(File[] selection) {
                if (selection.length > 1) {
                    return false;
                }
                return selection[0].getName().endsWith(".vtk") | selection[0].getName().endsWith(".VTK");
            }
        }).setApproveText(NbBundle.getMessage(VTKImportPanel.class, "OpenFileDialog.ApproveText")).setFileHiding(true).showOpenDialog();
        if (file != null) {
            filenameField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_openButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filenameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton openButton;
    private javax.swing.JFormattedTextField scaleFactorField;
    // End of variables declaration//GEN-END:variables
}
