/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.welcome;

import org.openide.util.NbBundle;

/**
 *
 * @author Andreas Hauffe
 */
public class FirstStepsPanel extends ContentPanel {

    /**
     * Creates new form FirstStepsPanel
     */
    @SuppressWarnings("this-escape")
    public FirstStepsPanel() {
        super(NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.title"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        step1IconLabel = new javax.swing.JLabel();
        step2IconLabel = new javax.swing.JLabel();
        step1HeadLabel = new javax.swing.JLabel();
        step2HeadLabel = new javax.swing.JLabel();
        step1TextLabel = new javax.swing.JLabel();
        step2TextLabel = new javax.swing.JLabel();
        orLabel = new javax.swing.JLabel();
        step1icon2Label = new javax.swing.JLabel();
        step1Text2Label = new javax.swing.JLabel();
        step3HeadLabel = new javax.swing.JLabel();
        step3TextLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        step1IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elamx/welcome/resources/NewMaterial.png"))); // NOI18N

        step2IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elamx/welcome/resources/NewLaminate.png"))); // NOI18N

        step1HeadLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step1HeadLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step1HeadLabel.text")); // NOI18N

        step2HeadLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step2HeadLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step2HeadLabel.text")); // NOI18N

        step1TextLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step1TextLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step1TextLabel.text")); // NOI18N
        step1TextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        step1TextLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        step2TextLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step2TextLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step2TextLabel.text")); // NOI18N
        step2TextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        step2TextLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        orLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(orLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.orLabel.text")); // NOI18N

        step1icon2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/elamx/welcome/resources/ImportMaterial.png"))); // NOI18N

        step1Text2Label.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step1Text2Label, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step1Text2Label.text")); // NOI18N
        step1Text2Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        step3HeadLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step3HeadLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step3HeadLabel.text")); // NOI18N

        step3TextLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(step3TextLabel, org.openide.util.NbBundle.getMessage(FirstStepsPanel.class, "FirstStepsPanel.step3TextLabel.text")); // NOI18N
        step3TextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        step3TextLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(step1HeadLabel)
                            .addComponent(step2HeadLabel)
                            .addComponent(step3HeadLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(step3TextLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(step1IconLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(step1TextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(orLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(step1icon2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(step1Text2Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(step2IconLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(step2TextLabel)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(step1HeadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(step1TextLabel)
                    .addComponent(step1IconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(step1Text2Label)
                    .addComponent(step1icon2Label))
                .addGap(18, 18, 18)
                .addComponent(step2HeadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(step2TextLabel)
                    .addComponent(step2IconLabel))
                .addGap(18, 18, 18)
                .addComponent(step3HeadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(step3TextLabel)
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel orLabel;
    private javax.swing.JLabel step1HeadLabel;
    private javax.swing.JLabel step1IconLabel;
    private javax.swing.JLabel step1Text2Label;
    private javax.swing.JLabel step1TextLabel;
    private javax.swing.JLabel step1icon2Label;
    private javax.swing.JLabel step2HeadLabel;
    private javax.swing.JLabel step2IconLabel;
    private javax.swing.JLabel step2TextLabel;
    private javax.swing.JLabel step3HeadLabel;
    private javax.swing.JLabel step3TextLabel;
    // End of variables declaration//GEN-END:variables
}
