/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.clt.calculation.layerproperties;

import de.elamx.core.GlobalProperties;
import de.elamx.laminate.Layer;
import java.text.DecimalFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Andreas Hauffe
 */
public class MaterialPropertiesPanel extends javax.swing.JPanel {

    private final Layer layer;
    private final DecimalFormat stiffnessFormat = GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STIFFNESS);

    /**
     * Creates new form MaterialPropertiesPanel
     */
    @SuppressWarnings("this-escape")
    public MaterialPropertiesPanel() {
        this(null);
    }

    @SuppressWarnings("this-escape")
    public MaterialPropertiesPanel(Layer layer) {
        super();
        this.layer = layer;

        initComponents();

        eparField.setValue(layer.getMaterial().getEpar());
        enorField.setValue(layer.getMaterial().getEnor());
        nueField.setValue(layer.getMaterial().getNue12());
        gField.setValue(layer.getMaterial().getG());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eparLabel = new javax.swing.JLabel();
        eparField = new javax.swing.JFormattedTextField();
        enorLabel = new javax.swing.JLabel();
        nueLabel = new javax.swing.JLabel();
        gLabel = new javax.swing.JLabel();
        enorField = new javax.swing.JFormattedTextField();
        gField = new javax.swing.JFormattedTextField();
        nueField = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(eparLabel, org.openide.util.NbBundle.getMessage(MaterialPropertiesPanel.class, "MaterialPropertiesPanel.eparLabel.text")); // NOI18N

        eparField.setEditable(false);
        eparField.setBorder(null);
        eparField.setColumns(8);
        eparField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(stiffnessFormat)));
        eparField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        org.openide.awt.Mnemonics.setLocalizedText(enorLabel, org.openide.util.NbBundle.getMessage(MaterialPropertiesPanel.class, "MaterialPropertiesPanel.enorLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(nueLabel, org.openide.util.NbBundle.getMessage(MaterialPropertiesPanel.class, "MaterialPropertiesPanel.nueLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(gLabel, org.openide.util.NbBundle.getMessage(MaterialPropertiesPanel.class, "MaterialPropertiesPanel.gLabel.text")); // NOI18N

        enorField.setEditable(false);
        enorField.setBorder(null);
        enorField.setColumns(8);
        enorField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(stiffnessFormat)));
        enorField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        gField.setEditable(false);
        gField.setBorder(null);
        gField.setColumns(8);
        gField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(stiffnessFormat)));
        gField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        nueField.setEditable(false);
        nueField.setBorder(null);
        nueField.setColumns(8);
        nueField.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(stiffnessFormat)));
        nueField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eparLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(eparField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eparLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eparField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField enorField;
    private javax.swing.JLabel enorLabel;
    private javax.swing.JFormattedTextField eparField;
    private javax.swing.JLabel eparLabel;
    private javax.swing.JFormattedTextField gField;
    private javax.swing.JLabel gLabel;
    private javax.swing.JFormattedTextField nueField;
    private javax.swing.JLabel nueLabel;
    // End of variables declaration//GEN-END:variables
}
