/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.export.Ansys;

import de.elamx.export.Export;
import de.elamx.export.ExportOptions;
import de.elamx.export.ExportOptionsPanel;
import de.elamx.laminate.Laminat;
import org.openide.util.NbPreferences;

/**
 *
 * @author Andreas Hauffe
 */
public class AnsysExportOptionsPanel extends ExportOptionsPanel {

    private Laminat laminate;
    
    /**
     * Creates new form AnsysExportOptionsPanel
     */
    public AnsysExportOptionsPanel() {
        initComponents();
    }
    
    public AnsysExportOptionsPanel(Laminat laminate) {
        this();
        this.laminate = laminate;
        hygrothermalCheckBox.setSelected(NbPreferences.forModule(AnsysExportOptionsPanel.class).getBoolean("AnsysExportOptionsPanel.hygrothermnal", false));
        strengthCheckBox.setSelected(NbPreferences.forModule(AnsysExportOptionsPanel.class).getBoolean("AnsysExportOptionsPanel.strength", false));
        realRadioButton.setSelected(NbPreferences.forModule(AnsysExportOptionsPanel.class).getBoolean("AnsysExportOptionsPanel.real", true));
        sectionRadioButton.setSelected(NbPreferences.forModule(AnsysExportOptionsPanel.class).getBoolean("AnsysExportOptionsPanel.section", false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        realRadioButton = new javax.swing.JRadioButton();
        sectionRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        hygrothermalCheckBox = new javax.swing.JCheckBox();
        strengthCheckBox = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "typePanel.title"))); // NOI18N

        buttonGroup1.add(realRadioButton);
        realRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(realRadioButton, org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "AnsysExportOptionsPanel.realRadioButton.text")); // NOI18N

        buttonGroup1.add(sectionRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(sectionRadioButton, org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "AnsysExportOptionsPanel.sectionRadioButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(realRadioButton)
                    .addComponent(sectionRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectionRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "additionalExportPanel.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hygrothermalCheckBox, org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "AnsysExportOptionsPanel.hygrothermalCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(strengthCheckBox, org.openide.util.NbBundle.getMessage(AnsysExportOptionsPanel.class, "AnsysExportOptionsPanel.strengthCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hygrothermalCheckBox)
                    .addComponent(strengthCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hygrothermalCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(strengthCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox hygrothermalCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton realRadioButton;
    private javax.swing.JRadioButton sectionRadioButton;
    private javax.swing.JCheckBox strengthCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public Export<? extends ExportOptions> getExport() {
        AnsysExport export = new AnsysExport(laminate);
        AnsysExportOptions options = export.getOptions();
        options.setHygrothermal(hygrothermalCheckBox.isSelected());
        options.setStrength(strengthCheckBox.isSelected());
        options.setExportType(realRadioButton.isSelected() == true ? AnsysExportOptions.TYPE_REAL : AnsysExportOptions.TYPE_SECTION);
        NbPreferences.forModule(AnsysExportOptionsPanel.class).putBoolean("AnsysExportOptionsPanel.hygrothermnal", hygrothermalCheckBox.isSelected());
        NbPreferences.forModule(AnsysExportOptionsPanel.class).putBoolean("AnsysExportOptionsPanel.strength", strengthCheckBox.isSelected());
        NbPreferences.forModule(AnsysExportOptionsPanel.class).putBoolean("AnsysExportOptionsPanel.real", realRadioButton.isSelected());
        NbPreferences.forModule(AnsysExportOptionsPanel.class).putBoolean("AnsysExportOptionsPanel.section", sectionRadioButton.isSelected());
        return export;
    }
}
