#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
if [ -d "$HERE/usr/lib/jre" ] ; then
  if [ -z "$JAVA_HOME" ] ; then
    export JAVA_HOME="$HERE/usr/lib/jre/"
  fi
  exec "$HERE/usr/bin/elamx2" --jdkhome "$HERE/usr/lib/jre" "$@"
else
  exec "$HERE/usr/bin/elamx2" "$@"
fi
