/*
 *  This program developed in Java is based on the netbeans platform and is used
 *  to design and to analyse composite structures by means of analytical and 
 *  numerical methods.
 * 
 *  Further information can be found here:
 *  http://www.elamx.de
 *    
 *  Copyright (C) 2021 Technische Universität Dresden - Andreas Hauffe
 * 
 *  This file is part of eLamX².
 *
 *  eLamX² is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  eLamX² is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with eLamX².  If not, see <http://www.gnu.org/licenses/>.
 */
package de.elamx.core.globalproperties;

import de.elamx.core.GlobalProperties;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.LifecycleManager;
import org.openide.awt.Notification;
import org.openide.awt.NotificationDisplayer;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

final class FormatPanel extends javax.swing.JPanel implements DocumentListener{

    private final FormatOptionsPanelController controller;
    private final DecimalFormat df = (DecimalFormat)NumberFormat.getNumberInstance();

    FormatPanel(FormatOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        youngsModulusField.getDocument().addDocumentListener(this);
        poissonRatioField.getDocument().addDocumentListener(this);
        thicknessField.getDocument().addDocumentListener(this);
        yieldStressField.getDocument().addDocumentListener(this);
        angleField.getDocument().addDocumentListener(this);
        densityField.getDocument().addDocumentListener(this);
        hygrothermField.getDocument().addDocumentListener(this);
        forceField.getDocument().addDocumentListener(this);
        stressField.getDocument().addDocumentListener(this);
        strainField.getDocument().addDocumentListener(this);
        displacementField.getDocument().addDocumentListener(this);
        frequencyField.getDocument().addDocumentListener(this);
        rfField.getDocument().addDocumentListener(this);
        percField.getDocument().addDocumentListener(this);
        eigenValField.getDocument().addDocumentListener(this);
        tempField.getDocument().addDocumentListener(this);
        doubleField.getDocument().addDocumentListener(this);
        smallDoubleField.getDocument().addDocumentListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        numberFormatPanel = new javax.swing.JPanel();
        emodulLabel = new javax.swing.JLabel();
        poissonsRatioLabel = new javax.swing.JLabel();
        thicknessLabel = new javax.swing.JLabel();
        yieldStressLabel = new javax.swing.JLabel();
        youngsModulusField = new javax.swing.JTextField();
        poissonRatioField = new javax.swing.JTextField();
        thicknessField = new javax.swing.JTextField();
        yieldStressField = new javax.swing.JTextField();
        angleLabel = new javax.swing.JLabel();
        angleField = new javax.swing.JTextField();
        densityLabel = new javax.swing.JLabel();
        hygrothermLabel = new javax.swing.JLabel();
        densityField = new javax.swing.JTextField();
        hygrothermField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        forceLabel = new javax.swing.JLabel();
        forceField = new javax.swing.JTextField();
        stressLabel = new javax.swing.JLabel();
        stressField = new javax.swing.JTextField();
        strainLabel = new javax.swing.JLabel();
        strainField = new javax.swing.JTextField();
        displacementLabel = new javax.swing.JLabel();
        displacementField = new javax.swing.JTextField();
        frequencyLabel = new javax.swing.JLabel();
        frequencyField = new javax.swing.JTextField();
        rfLabel = new javax.swing.JLabel();
        rfField = new javax.swing.JTextField();
        percLabel = new javax.swing.JLabel();
        percField = new javax.swing.JTextField();
        eigValLabel = new javax.swing.JLabel();
        eigenValField = new javax.swing.JTextField();
        tempLabel = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        tempLabel1 = new javax.swing.JLabel();
        smallDoubleField = new javax.swing.JTextField();
        doubleLabel = new javax.swing.JLabel();
        doubleField = new javax.swing.JTextField();
        englishFormatCheckBox = new javax.swing.JCheckBox();
        transShearCheckBox = new javax.swing.JCheckBox();

        numberFormatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.numberFormatPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(emodulLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.emodulLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(poissonsRatioLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.poissonsRatioLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(thicknessLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.thicknessLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(yieldStressLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.yieldStressLabel.text")); // NOI18N

        youngsModulusField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        youngsModulusField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.youngsModulusField.text")); // NOI18N

        poissonRatioField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        poissonRatioField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.poissonRatioField.text")); // NOI18N

        thicknessField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        thicknessField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.thicknessField.text")); // NOI18N

        yieldStressField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        yieldStressField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.yieldStressField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(angleLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.angleLabel.text")); // NOI18N

        angleField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        angleField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.angleField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(densityLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.densityLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(hygrothermLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.hygrothermLabel.text")); // NOI18N

        densityField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        densityField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.densityField.text")); // NOI18N

        hygrothermField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        hygrothermField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.hygrothermField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(forceLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.forceLabel.text")); // NOI18N

        forceField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        forceField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.forceField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(stressLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.stressLabel.text")); // NOI18N

        stressField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        stressField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.stressField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(strainLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.strainLabel.text")); // NOI18N

        strainField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        strainField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.strainField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(displacementLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.displacementLabel.text")); // NOI18N

        displacementField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        displacementField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.displacementField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(frequencyLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.frequencyLabel.text")); // NOI18N

        frequencyField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        frequencyField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.frequencyField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rfLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.rfLabel.text")); // NOI18N

        rfField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        rfField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.rfField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(percLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.percLabel.text")); // NOI18N

        percField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        percField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.percField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(eigValLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.eigValLabel.text")); // NOI18N

        eigenValField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        eigenValField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.eigenValField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tempLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.tempLabel.text")); // NOI18N

        tempField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tempField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.tempField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tempLabel1, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.tempLabel1.text")); // NOI18N

        smallDoubleField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        smallDoubleField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.smallDoubleField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(doubleLabel, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.doubleLabel.text")); // NOI18N

        doubleField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        doubleField.setText(org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.doubleField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(englishFormatCheckBox, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.englishFormatCheckBox.text")); // NOI18N
        englishFormatCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishFormatCheckBoxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(transShearCheckBox, org.openide.util.NbBundle.getMessage(FormatPanel.class, "FormatPanel.transShearCheckBox.text")); // NOI18N
        transShearCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transShearCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numberFormatPanelLayout = new javax.swing.GroupLayout(numberFormatPanel);
        numberFormatPanel.setLayout(numberFormatPanelLayout);
        numberFormatPanelLayout.setHorizontalGroup(
            numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberFormatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transShearCheckBox)
                    .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(numberFormatPanelLayout.createSequentialGroup()
                            .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(doubleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(forceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hygrothermLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(angleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emodulLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(poissonsRatioLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thicknessLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yieldStressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(densityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(doubleField)
                                .addComponent(youngsModulusField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(poissonRatioField)
                                .addComponent(thicknessField)
                                .addComponent(yieldStressField)
                                .addComponent(angleField)
                                .addComponent(densityField)
                                .addComponent(hygrothermField)
                                .addComponent(forceField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(displacementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(strainLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(stressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(frequencyLabel)
                                .addComponent(rfLabel)
                                .addComponent(percLabel)
                                .addComponent(eigValLabel)
                                .addComponent(tempLabel)
                                .addComponent(tempLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(stressField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(strainField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(displacementField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(frequencyField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(rfField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(percField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(eigenValField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(tempField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(smallDoubleField))))
                    .addComponent(englishFormatCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        numberFormatPanelLayout.setVerticalGroup(
            numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberFormatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numberFormatPanelLayout.createSequentialGroup()
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emodulLabel)
                            .addComponent(youngsModulusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poissonsRatioLabel)
                            .addComponent(poissonRatioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thicknessLabel)
                            .addComponent(thicknessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yieldStressLabel)
                            .addComponent(yieldStressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angleLabel)
                            .addComponent(angleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(densityLabel)
                            .addComponent(densityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hygrothermLabel)
                            .addComponent(hygrothermField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forceLabel)
                            .addComponent(forceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(numberFormatPanelLayout.createSequentialGroup()
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stressLabel)
                            .addComponent(stressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strainLabel)
                            .addComponent(strainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displacementLabel)
                            .addComponent(displacementField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frequencyLabel)
                            .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rfLabel)
                            .addComponent(rfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(percLabel)
                            .addComponent(percField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eigValLabel)
                            .addComponent(eigenValField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempLabel)
                            .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numberFormatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doubleLabel)
                        .addComponent(doubleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tempLabel1))
                    .addComponent(smallDoubleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(englishFormatCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transShearCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(numberFormatPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void englishFormatCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishFormatCheckBoxActionPerformed
        controller.changed();
    }//GEN-LAST:event_englishFormatCheckBoxActionPerformed

    private void transShearCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transShearCheckBoxActionPerformed
        controller.changed();
    }//GEN-LAST:event_transShearCheckBoxActionPerformed

    void load() {
        youngsModulusField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STIFFNESS).toPattern());
        poissonRatioField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_POISSONRATIO).toPattern());
        thicknessField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_THICKNESS).toPattern());
        angleField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_ANGLE).toPattern());
        densityField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DENSITY).toPattern());
        hygrothermField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_HYGROTHERMCOEFF).toPattern());
        yieldStressField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_YIELDSTRESS).toPattern());
        forceField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_FORCE).toPattern());
        stressField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STRESS).toPattern());
        strainField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STRAIN).toPattern());
        displacementField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DISPLACEMENT).toPattern());
        frequencyField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_FREQUENCY).toPattern());
        rfField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_RESERVE_FACTOR).toPattern());
        percField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_PERCENT).toPattern());
        eigenValField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_EIGENVALUE).toPattern());
        tempField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_TEMPERATURE).toPattern());
        doubleField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DOUBLE).toPattern());
        smallDoubleField.setText(GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_SMALL_DOUBLE).toPattern());
        englishFormatCheckBox.setSelected(GlobalProperties.getDefault().isUseENUS());
        transShearCheckBox.setSelected(GlobalProperties.getDefault().isShowTransShear());
    }

    void store() {
        String temp = youngsModulusField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STIFFNESS).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_STIFFNESS, temp);
        
        temp = poissonRatioField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_POISSONRATIO).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_POISSONRATIO, temp);
        
        temp = thicknessField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_THICKNESS).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_THICKNESS, temp);
        
        temp = yieldStressField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_YIELDSTRESS).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_YIELDSTRESS, temp);
        
        temp = angleField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_ANGLE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_ANGLE, temp);
        
        temp = densityField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DENSITY).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_DENSITY, temp);
        
        temp = hygrothermField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_HYGROTHERMCOEFF).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_HYGROTHERMCOEFF, temp);
        
        temp = forceField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_FORCE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_FORCE, temp);
        
        temp = stressField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STRESS).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_STRESS, temp);
        
        temp = strainField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_STRAIN).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_STRAIN, temp);
        
        temp = displacementField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DISPLACEMENT).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_DISPLACEMENT, temp);
        
        temp = frequencyField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_FREQUENCY).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_FREQUENCY, temp);
        
        temp = rfField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_RESERVE_FACTOR).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_RESERVE_FACTOR, temp);
        
        temp = percField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_PERCENT).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_PERCENT, temp);
        
        temp = eigenValField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_EIGENVALUE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_EIGENVALUE, temp);
        
        temp = tempField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_TEMPERATURE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_TEMPERATURE, temp);
        
        temp = doubleField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_DOUBLE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_DOUBLE, temp);
        
        temp = smallDoubleField.getText();
        GlobalProperties.getDefault().getFormat(GlobalProperties.FORMAT_SMALL_DOUBLE).applyPattern(temp);
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.FORMAT_SMALL_DOUBLE, temp);
        
        GlobalProperties.getDefault().useUSLocale(englishFormatCheckBox.isSelected());
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.USE_enUS_LOCALE, Boolean.toString(englishFormatCheckBox.isSelected()));
        
        GlobalProperties.getDefault().setShowTransShear(transShearCheckBox.isSelected());
        NbPreferences.forModule(FormatPanel.class).put(GlobalProperties.SHOW_TRANSVERSAL_SHEAR, Boolean.toString(transShearCheckBox.isSelected()));
        
        askForRestart();
    }    
    
    private static Notification restartNotification;

    private void askForRestart() {
        if( null != restartNotification ) {
            restartNotification.clear();
        }
        restartNotification = NotificationDisplayer.getDefault().notify( NbBundle.getMessage(FormatPanel.class, "Hint_RESTART_IDE"),
                ImageUtilities.loadImageIcon( "org/netbeans/core/windows/resources/restart.png", true ), //NOI18N
                createRestartNotificationDetails(), createRestartNotificationDetails(),
                NotificationDisplayer.Priority.HIGH, NotificationDisplayer.Category.INFO);
    }    
    
    private JComponent createRestartNotificationDetails() {
        JPanel res = new JPanel( new BorderLayout( 10, 10) );
        res.setOpaque( false );
        JLabel lbl = new JLabel( NbBundle.getMessage( FormatPanel.class, "Descr_Restart") ); //NOI18N
        lbl.setCursor( Cursor.getPredefinedCursor( Cursor.HAND_CURSOR ) );
        res.add( lbl, BorderLayout.CENTER );
        lbl.addMouseListener( new MouseAdapter() {
            @Override
            public void mouseClicked( MouseEvent e ) {
                if( null != restartNotification ) {
                    restartNotification.clear();
                    restartNotification = null;
                }
                LifecycleManager.getDefault().markForRestart();
                LifecycleManager.getDefault().exit();
            }
        });
        return res;
    }

    boolean valid() {
        try{
            df.applyPattern(youngsModulusField.getText());
            df.applyPattern(poissonRatioField.getText());
            df.applyPattern(thicknessField.getText());
            df.applyPattern(yieldStressField.getText());
            df.applyPattern(angleField.getText());
            df.applyPattern(densityField.getText());
            df.applyPattern(hygrothermField.getText());
            df.applyPattern(forceField.getText());
            df.applyPattern(stressField.getText());
            df.applyPattern(strainField.getText());
            df.applyPattern(displacementField.getText());
            df.applyPattern(frequencyField.getText());
            df.applyPattern(rfField.getText());
            df.applyPattern(percField.getText());
            df.applyPattern(eigenValField.getText());
            df.applyPattern(tempField.getText());
            df.applyPattern(doubleField.getText());
            df.applyPattern(smallDoubleField.getText());
        }catch(IllegalArgumentException ex){
            return false;
        }
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angleField;
    private javax.swing.JLabel angleLabel;
    private javax.swing.JTextField densityField;
    private javax.swing.JLabel densityLabel;
    private javax.swing.JTextField displacementField;
    private javax.swing.JLabel displacementLabel;
    private javax.swing.JTextField doubleField;
    private javax.swing.JLabel doubleLabel;
    private javax.swing.JLabel eigValLabel;
    private javax.swing.JTextField eigenValField;
    private javax.swing.JLabel emodulLabel;
    private javax.swing.JCheckBox englishFormatCheckBox;
    private javax.swing.JTextField forceField;
    private javax.swing.JLabel forceLabel;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JTextField hygrothermField;
    private javax.swing.JLabel hygrothermLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel numberFormatPanel;
    private javax.swing.JTextField percField;
    private javax.swing.JLabel percLabel;
    private javax.swing.JTextField poissonRatioField;
    private javax.swing.JLabel poissonsRatioLabel;
    private javax.swing.JTextField rfField;
    private javax.swing.JLabel rfLabel;
    private javax.swing.JTextField smallDoubleField;
    private javax.swing.JTextField strainField;
    private javax.swing.JLabel strainLabel;
    private javax.swing.JTextField stressField;
    private javax.swing.JLabel stressLabel;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel tempLabel1;
    private javax.swing.JTextField thicknessField;
    private javax.swing.JLabel thicknessLabel;
    private javax.swing.JCheckBox transShearCheckBox;
    private javax.swing.JTextField yieldStressField;
    private javax.swing.JLabel yieldStressLabel;
    private javax.swing.JTextField youngsModulusField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        controller.changed();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        controller.changed();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        controller.changed();
    }
}
