name: delete-old-assets-nightly-manual

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: nightly # This may also be of the form 'refs/tags/staging'

          # Optional another repository
          repository: AndiMb/eLamX2

          assets: |
            eLamX.3.0.0.exe
#            eLamX2-x86_64.AppImage
#            elamx2_linux.zip
#            elamx2_macos.zip
#            elamx2_windows.zip
