
name: Build installer

on: [workflow_dispatch]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml build-zip-with_jre

    - name: Upload Linux Zip
      uses: actions/upload-artifact@v3
      with:
        name: elamx-macos-zip
        path: "dist/*.zip"
        retention-days: 1
