# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: cjmach/setup-netbeans-action@v2.1
      name: Setup NetBeans distribution
      with:
        version: '26'
    - name: Test with Ant
      run: >-
        ant -noinput -buildfile build.xml
        -Dnbplatform.default.netbeans.dest.dir=${{ github.workspace }}/netbeans
        -Dnbplatform.default.harness.dir=${{ github.workspace }}/netbeans/harness
        test
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Ant Tests
        path: ./**/build/test/unit/results/*.xml
        reporter: java-junit
        fail-on-error: true