
name: Build installer

on: [workflow_dispatch]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml windows-installer

#    - name: Sign die Installer
#      uses: AndiMb/code-sign-action@v1
#      with:
#        certificate: '${{ secrets.CERTIFICATE }}'
#        password: '${{ secrets.PASSWORD }}'
#        certificatename: '${{ secrets.CERTNAME }}'
#        timestampUrl: 'http://timestamp.digicert.com'
#        folder: "dist"

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v3
      with:
        name: elamx-windows
        path: "dist/*.exe"
        retention-days: 1

    - name: Upload Windows Zip
      uses: actions/upload-artifact@v3
      with:
        name: elamx-windows-zip
        path: "dist/*.zip"
        retention-days: 1

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install xmllint
      run: sudo apt-get install -y libfuse2

    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml linux-appimage

    - name: Upload Linux AppIamge
      uses: actions/upload-artifact@v3
      with:
        name: elamx-linux-appimage
        path: "dist/eLamX2-x86_64.AppImage"
        retention-days: 1

    - name: Upload Linux Zip
      uses: actions/upload-artifact@v3
      with:
        name: elamx-linux-zip
        path: "dist/*.zip"
        retention-days: 1
