
name: windows-installer

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml windows-installer

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v3
      with:
        name: elamx
        path: "dist/*.exe"
